apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  type: NodePort
  selector:
    app: excalidraw
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
